name: Github Pages

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Setup rust # setup rust toolchain for wasm
      uses: dtolnay/rust-toolchain@nightly
      with:
        target: wasm32-unknown-unknown
    - name: Cache rust # cache the rust build artefacts
      uses: Swatinem/rust-cache@v2
    - name: Download and install trunk
      run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
    - name: Build
      run: ./trunk build --release --filehash=false --public-url=$public_url
      env:
        public_url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        single-commit: true
